CREATE SCHEMA IF NOT EXISTS "command_side";

CREATE TABLE IF NOT EXISTS "command_side"."domainevententry"
(
    GLOBALINDEX            BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL,
    EVENTIDENTIFIER        VARCHAR(255) NOT NULL,
    AGGREGATEIDENTIFIER    VARCHAR(255) NOT NULL,   -- Unique ID for the aggregate.
    SEQUENCENUMBER         BIGINT NOT NULL,         -- Sequence number of the event for the specific aggregate.
    TYPE                   VARCHAR(255) NOT NULL,   -- Aggregate type.
    PAYLOADTYPE            VARCHAR(255) NOT NULL,   -- Fully qualified type name of the actual event payload.
    PAYLOADREVISION        VARCHAR(255),
    PAYLOAD                jsonb NOT NULL,          -- Serialized event payload of the given payload_type.
    TIMESTAMP              VARCHAR(255) NOT NULL,   -- Event timestamp.
    METADATA               jsonb,                   -- Any metadata (such as traceIds associated with the event).
    PRIMARY KEY (GLOBALINDEX)
);

CREATE UNIQUE INDEX DOMAINEVENTENTRY_UNIQUE_INDEX_AGGREGATE
    ON "command_side"."domainevententry"(AGGREGATEIDENTIFIER, SEQUENCENUMBER);

CREATE UNIQUE INDEX DOMAINEVENTENTRY_UNIQUE_INDEX_EVENT
    ON "command_side"."domainevententry" (EVENTIDENTIFIER);

CREATE TABLE IF NOT EXISTS "command_side"."snapshotevententry"
(
    SEQUENCENUMBER         BIGINT NOT NULL,
    AGGREGATEIDENTIFIER    VARCHAR(255) NOT NULL,
    TYPE                   VARCHAR(255) NOT NULL,
    EVENTIDENTIFIER        VARCHAR(255) NOT NULL,
    METADATA               jsonb,
    PAYLOAD                jsonb NOT NULL,
    PAYLOADREVISION        VARCHAR(255),
    PAYLOADTYPE            VARCHAR(255) NOT NULL,
    TIMESTAMP              VARCHAR(255) NOT NULL,
    PRIMARY KEY (AGGREGATEIDENTIFIER, SEQUENCENUMBER),
    UNIQUE (EVENTIDENTIFIER)
);

CREATE TABLE IF NOT EXISTS "command_side"."eventsourcing_sequence"
(
    SEQ_NAME VARCHAR(50) NOT NULL,
    SEQ_COUNT NUMERIC(38),
    PRIMARY KEY (SEQ_NAME)
);

CREATE TABLE IF NOT EXISTS "command_side"."sagaentry"
(
    sagaId         VARCHAR(255) NOT NULL,
    revision       VARCHAR(255),
    sagaType       VARCHAR(255),
    serializedSaga bytea,
    PRIMARY KEY (sagaId)
);

CREATE TABLE IF NOT EXISTS "command_side"."associationvalueentry"
(
    id               INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL,
    associationKey   VARCHAR(255),
    associationValue VARCHAR(255),
    sagaId           VARCHAR(255),
    sagaType         VARCHAR(255),
    PRIMARY KEY (id)
);

CREATE INDEX IF NOT EXISTS ASSOCIATIONVALUEENTRY_INDEX_ASSOCIATION
    ON "command_side"."associationvalueentry" (sagaType, associationKey, associationValue);

CREATE INDEX IF NOT EXISTS ASSOCIATIONVALUEENTRY_INDEX_SAGA
    ON "command_side"."associationvalueentry" (sagaId, sagaType);

INSERT INTO "command_side"."eventsourcing_sequence"(SEQ_NAME, SEQ_COUNT) values
(
    'ASSOCIATIONVALUEENTRY_ID', 0
);

INSERT INTO "command_side"."eventsourcing_sequence"(SEQ_NAME, SEQ_COUNT) values
(
    'DOMAINEVENTENTRY_GLOBAL_INDEX', 0
);